export const mockData = [
    { name: "notebook", price: 5.99, quantity: 3, isExempt: false },
    { name: "pen", price: 1.49, quantity: 10, isExempt: false },
    { name: "pencil", price: 0.99, quantity: 12, isExempt: false },
    { name: "headphones", price: 29.99, quantity: 2, isExempt: false },
    { name: "milk", price: 2.49, quantity: 4, isExempt: true }, 
    { name: "bread", price: 1.99, quantity: 5, isExempt: true }, 
    { name: "sugar", price: 3.49, quantity: 2, isExempt: true }, 
    { name: "smartphone", price: 699.99, quantity: 1, isExempt: false },
    { name: "watch", price: 149.99, quantity: 1, isExempt: false },
    { name: "coffee", price: 4.99, quantity: 2, isExempt: true }, 
    { name: "shampoo", price: 6.99, quantity: 3, isExempt: false },
    { name: "toothpaste", price: 2.99, quantity: 3, isExempt: false },
    { name: "t-shirt", price: 14.99, quantity: 5, isExempt: false },
    { name: "jeans", price: 49.99, quantity: 2, isExempt: false },
    { name: "jacket", price: 89.99, quantity: 1, isExempt: false },
    { name: "gloves", price: 19.99, quantity: 2, isExempt: false },
    { name: "chocolate bar", price: 0.99, quantity: 6, isExempt: true }, 
    { name: "sneakers", price: 79.99, quantity: 1, isExempt: false },
    { name: "sandals", price: 39.99, quantity: 1, isExempt: false },
    { name: "printer", price: 129.99, quantity: 1, isExempt: false },
    { name: "paper", price: 4.99, quantity: 2, isExempt: false },
    { name: "pasta", price: 1.29, quantity: 8, isExempt: true }, 
    { name: "rice", price: 2.49, quantity: 4, isExempt: true }, 
    { name: "tomato sauce", price: 1.99, quantity: 6, isExempt: true }, 
    { name: "keyboard", price: 49.99, quantity: 1, isExempt: false },
    { name: "mouse", price: 29.99, quantity: 1, isExempt: false },
    { name: "monitor", price: 199.99, quantity: 1, isExempt: false },
    { name: "tablet", price: 299.99, quantity: 1, isExempt: false },
    { name: "usb drive", price: 14.99, quantity: 3, isExempt: false },
    { name: "external hard drive", price: 89.99, quantity: 1, isExempt: false },
    { name: "yogurt", price: 3.99, quantity: 5, isExempt: true }, 
    { name: "cheese", price: 5.99, quantity: 2, isExempt: true }, 
    { name: "butter", price: 2.99, quantity: 2, isExempt: true }, 
    { name: "chicken breast", price: 6.99, quantity: 3, isExempt: true }, 
    { name: "beef steak", price: 12.99, quantity: 2, isExempt: true }, 
    { name: "salmon", price: 14.99, quantity: 2, isExempt: true }, 
    { name: "bandages", price: 4.49, quantity: 2, isExempt: true }, 
    { name: "pain reliever", price: 8.99, quantity: 3, isExempt: true }, 
    { name: "vitamins", price: 11.99, quantity: 2, isExempt: true }, 
    { name: "antibiotic cream", price: 5.99, quantity: 2, isExempt: true }, 
    { name: "face mask", price: 9.99, quantity: 5, isExempt: false },
    { name: "hair dryer", price: 49.99, quantity: 1, isExempt: false },
    { name: "electric shaver", price: 79.99, quantity: 1, isExempt: false },
    { name: "book - fiction", price: 15.99, quantity: 3, isExempt: true }, 
    { name: "book - history", price: 20.99, quantity: 2, isExempt: true }, 
    { name: "water bottle", price: 1.49, quantity: 6, isExempt: false },
    { name: "energy drink", price: 2.99, quantity: 3, isExempt: true }, 
    { name: "cereal", price: 4.99, quantity: 3, isExempt: true }, 
    { name: "honey", price: 6.49, quantity: 2, isExempt: true }, 
    { name: "tea", price: 3.49, quantity: 2, isExempt: true }, 
    { name: "salt", price: 1.99, quantity: 4, isExempt: true }, 
    { name: "pepper", price: 2.99, quantity: 3, isExempt: true }, 
    { name: "cooking oil", price: 8.99, quantity: 2, isExempt: true }, 
    { name: "spaghetti", price: 1.89, quantity: 7, isExempt: true }, 
    { name: "socks", price: 9.99, quantity: 3, isExempt: false },
    { name: "wallet", price: 29.99, quantity: 1, isExempt: false },
    { name: "belt", price: 19.99, quantity: 2, isExempt: false },
    { name: "hat", price: 14.99, quantity: 2, isExempt: false },
    { name: "perfume", price: 39.99, quantity: 1, isExempt: false },
    { name: "sunscreen", price: 9.99, quantity: 2, isExempt: false },
    { name: "deodorant", price: 4.99, quantity: 3, isExempt: false },
    { name: "lotion", price: 7.99, quantity: 2, isExempt: false }
  ];